osx_image: xcode10.2
language: swift
xcode_project: seatsio-ios.xcodeproj # path to your xcodeproj folder
xcode_scheme: MyNewProjectTests
xcode_destination: platform=iOS Simulator,OS=10.1,name=iPad Pro (9.7-inch)
before_install:
  - gem install cocoapods
script:
  - pod lib lint
deploy:
  provider: script
  script: ./deploy.sh
  on:
    tags: true